CREATE TYPE "AcademicPeriodStatus" AS ENUM ('PLANNED', 'ACTIVE', 'CLOSED');
CREATE TABLE "AcademicYear" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "name" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "status" "AcademicPeriodStatus" NOT NULL DEFAULT 'PLANNED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AcademicYear_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AcademicTerm" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "academicYearId" TEXT NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "status" "AcademicPeriodStatus" NOT NULL DEFAULT 'PLANNED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AcademicTerm_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Department" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Department_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Program" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "departmentId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "degreeType" TEXT, "requiredCredits" DOUBLE PRECISION, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Program_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GradeLevel" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "order" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GradeLevel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Subject" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Subject_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CreditPolicy" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "name" TEXT NOT NULL, "contactHoursPerCredit" DOUBLE PRECISION NOT NULL, "minCredits" DOUBLE PRECISION, "maxCredits" DOUBLE PRECISION, "isDefault" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CreditPolicy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Campus" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Campus_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Building" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "campusId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Building_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Room" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "buildingId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "capacity" INTEGER, "type" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Room_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Holiday" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "termId" TEXT, "name" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "isTeachingDay" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Holiday_pkey" PRIMARY KEY ("id"));
ALTER TABLE "Course" ADD COLUMN "subjectId" TEXT;
ALTER TABLE "Schedule" ADD COLUMN "termId" TEXT, ADD COLUMN "roomId" TEXT;
CREATE UNIQUE INDEX "AcademicYear_organizationId_name_key" ON "AcademicYear"("organizationId","name");
CREATE UNIQUE INDEX "AcademicTerm_organizationId_code_key" ON "AcademicTerm"("organizationId","code");
CREATE UNIQUE INDEX "Department_organizationId_code_key" ON "Department"("organizationId","code");
CREATE UNIQUE INDEX "Program_organizationId_code_key" ON "Program"("organizationId","code");
CREATE UNIQUE INDEX "GradeLevel_organizationId_code_key" ON "GradeLevel"("organizationId","code");
CREATE UNIQUE INDEX "GradeLevel_organizationId_order_key" ON "GradeLevel"("organizationId","order");
CREATE UNIQUE INDEX "Subject_organizationId_code_key" ON "Subject"("organizationId","code");
CREATE UNIQUE INDEX "CreditPolicy_organizationId_name_key" ON "CreditPolicy"("organizationId","name");
CREATE UNIQUE INDEX "Campus_organizationId_code_key" ON "Campus"("organizationId","code");
CREATE UNIQUE INDEX "Building_organizationId_campusId_code_key" ON "Building"("organizationId","campusId","code");
CREATE UNIQUE INDEX "Room_organizationId_buildingId_code_key" ON "Room"("organizationId","buildingId","code");
CREATE INDEX "Schedule_termId_idx" ON "Schedule"("termId"); CREATE INDEX "Schedule_roomId_idx" ON "Schedule"("roomId"); CREATE INDEX "Holiday_organizationId_startDate_idx" ON "Holiday"("organizationId","startDate");
ALTER TABLE "AcademicYear" ADD CONSTRAINT "AcademicYear_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AcademicTerm" ADD CONSTRAINT "AcademicTerm_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Department" ADD CONSTRAINT "Department_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Program" ADD CONSTRAINT "Program_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Program" ADD CONSTRAINT "Program_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GradeLevel" ADD CONSTRAINT "GradeLevel_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Subject" ADD CONSTRAINT "Subject_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CreditPolicy" ADD CONSTRAINT "CreditPolicy_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Campus" ADD CONSTRAINT "Campus_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Building" ADD CONSTRAINT "Building_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Room" ADD CONSTRAINT "Room_buildingId_fkey" FOREIGN KEY ("buildingId") REFERENCES "Building"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Holiday" ADD CONSTRAINT "Holiday_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Holiday" ADD CONSTRAINT "Holiday_termId_fkey" FOREIGN KEY ("termId") REFERENCES "AcademicTerm"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_termId_fkey" FOREIGN KEY ("termId") REFERENCES "AcademicTerm"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "Room"("id") ON DELETE SET NULL ON UPDATE CASCADE;
