export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  FINANCE = 'FINANCE',
}

export enum SubscriptionTier {
  FREE = 'FREE',
  BASIC = 'BASIC',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum EventTypes {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ENROLLMENT_CREATED = 'ENROLLMENT_CREATED',
  ASSIGNMENT_SUBMITTED = 'ASSIGNMENT_SUBMITTED',
  GRADE_PUBLISHED = 'GRADE_PUBLISHED',
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
}

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export * from './events';
export * from './roles';
