export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  PRINCIPAL = 'PRINCIPAL',
  INSTRUCTOR = 'INSTRUCTOR',
  STAFF = 'STAFF',
  FINANCE = 'FINANCE',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}
