import {useCallback,useEffect,useRef,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {AlertTriangle,CheckCircle2,Cloud,CloudOff} from 'lucide-react';import {recordQuizAudit,resumeQuizAttempt,saveQuizAnswer,submitQuizAttempt} from '../../services/api';import useAsyncAction from '../../hooks/useAsyncAction';import {useConfirm} from '../../components/ui/ConfirmDialog';
export default function ExamRunner(){const {attemptId}=useParams();const nav=useNavigate();const [attempt,setAttempt]=useState(null);const [answers,setAnswers]=useState({});const [index,setIndex]=useState(0);const [online,setOnline]=useState(navigator.onLine);const [saved,setSaved]=useState('');const timers=useRef({});const {run,pending}=useAsyncAction();const confirm=useConfirm();
useEffect(()=>{resumeQuizAttempt(attemptId).then(a=>{setAttempt(a);const restored=Object.fromEntries(a.answers.map(x=>[x.questionId,JSON.parse(x.answerJson)]));a.quiz.questions.forEach(q=>{const local=localStorage.getItem(`exam-${attemptId}-${q.id}`);if(local)try{restored[q.id]=JSON.parse(local)}catch{/* ignore malformed local draft */}});setAnswers(restored);});const on=()=>{setOnline(true);recordQuizAudit(attemptId,'RECONNECTED');};const off=()=>setOnline(false);const blur=()=>recordQuizAudit(attemptId,'FOCUS_LOST');window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('blur',blur);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('blur',blur);};},[attemptId]);
useEffect(()=>{const keys=e=>{if(e.altKey&&e.key==='ArrowRight')setIndex(i=>Math.min(i+1,(attempt?.quiz.questions.length||1)-1));if(e.altKey&&e.key==='ArrowLeft')setIndex(i=>Math.max(i-1,0));};window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[attempt]);
useEffect(()=>{if(!online||!attempt)return;attempt.quiz.questions.forEach(q=>{const key=`exam-${attemptId}-${q.id}`;const draft=localStorage.getItem(key);if(draft)try{saveQuizAnswer(attemptId,q.id,JSON.parse(draft)).then(()=>localStorage.removeItem(key)).catch(()=>{});}catch{/* keep malformed/offline draft for recovery */}});},[online,attempt,attemptId]);
const change=(q,value)=>{setAnswers(a=>({...a,[q.id]:value}));localStorage.setItem(`exam-${attemptId}-${q.id}`,JSON.stringify(value));clearTimeout(timers.current[q.id]);timers.current[q.id]=setTimeout(()=>saveQuizAnswer(attemptId,q.id,value).then(()=>{setSaved(new Date().toLocaleTimeString());localStorage.removeItem(`exam-${attemptId}-${q.id}`);}).catch(()=>setOnline(false)),700);};
// The server independently enforces expiry (QuizAttempt.expiresAt, computed at start) —
// this timer/auto-submit is purely a client convenience so the student isn't left staring
// at a dead form; a missed auto-submit still gets closed out server-side on the next
// autosave/resume call or the periodic expireDueAttempts sweep.
const answersRef=useRef(answers);useEffect(()=>{answersRef.current=answers;},[answers]);
const autoSubmitted=useRef(false);
const [remainingMs,setRemainingMs]=useState(null);
const doSubmit=useCallback(async()=>{await Promise.allSettled(Object.entries(answersRef.current).map(([qid,a])=>saveQuizAnswer(attemptId,qid,a)));await submitQuizAttempt(attemptId);nav(`/student/exams/${attemptId}/result`);},[attemptId,nav]);
useEffect(()=>{const expiresAt=attempt?.expiresAt;if(!expiresAt)return;const tick=()=>{const ms=new Date(expiresAt).getTime()-Date.now();setRemainingMs(ms);if(ms<=0&&!autoSubmitted.current){autoSubmitted.current=true;doSubmit().catch(()=>nav('/student/quizzes'));}};tick();const t=setInterval(tick,1000);return()=>clearInterval(t);},[attempt?.expiresAt,doSubmit,nav]);
const submit=async()=>{if(!await confirm('Шалгалтаа илгээх үү?'))return;run(doSubmit);};
if(!attempt)return <p role="status">Шалгалтыг сэргээж байна...</p>;const q=attempt.quiz.questions[index];const selected=answers[q.id]??(q.type==='MULTIPLE_SELECT'?[]:'');const multi=q.type==='MULTIPLE_SELECT';
const fmtClock=ms=>{const s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
const urgent=remainingMs!=null&&remainingMs<=60000;
const timeLabel=remainingMs!=null?`Үлдсэн хугацаа: ${fmtClock(remainingMs)}`:(attempt.quiz.timeLimitMins?`Хугацаа: ${attempt.quiz.timeLimitMins} минут`:'Хугацаагүй шалгалт');
return <main className="max-w-4xl mx-auto space-y-5" aria-labelledby="exam-title"><header className="panel sticky top-0 z-10"><div className="flex justify-between gap-4"><div><h1 id="exam-title" className="font-bold text-xl">{attempt.quiz.title}</h1><p className={`text-sm font-semibold ${urgent?'text-rose-700':'text-slate-600'}`} aria-live="polite">{timeLabel}</p><p aria-live="polite" className="text-sm text-slate-500">Асуулт {index+1}/{attempt.quiz.questions.length} · {online?<span className="text-emerald-700"><Cloud className="inline" size={15} aria-hidden/> online {saved&&`· ${saved}-д хадгалсан`}</span>:<span className="text-amber-700"><CloudOff className="inline" size={15} aria-hidden/> offline — дахин холбогдоход хадгална</span>}</p></div><button disabled={pending} className="btn-primary disabled:opacity-50" onClick={submit}><CheckCircle2 size={16} aria-hidden/>{pending?'Илгээж байна...':'Илгээх'}</button></div></header>
<section className="panel"><fieldset><legend className="text-lg font-semibold">{q.text} <span className="text-sm text-slate-500">({q.points} оноо)</span></legend>{['SINGLE_CHOICE','MULTIPLE_CHOICE','MULTIPLE_SELECT','TRUE_FALSE'].includes(q.type)?<div className="mt-5 space-y-3">{(q.type==='TRUE_FALSE'?[{id:'true',text:'Үнэн'},{id:'false',text:'Худал'}]:q.options).map(o=><label key={o.id} className="flex gap-3 p-3 border rounded-lg focus-within:ring-2 ring-indigo-500"><input type={multi?'checkbox':'radio'} name={q.id} checked={multi?selected.includes(o.id):selected===o.id} onChange={()=>change(q,multi?(selected.includes(o.id)?selected.filter(x=>x!==o.id):[...selected,o.id]):o.id)}/><span>{o.text}</span></label>)}</div>:q.type==='ESSAY'?<textarea autoFocus aria-label="Эсээ хариулт" className="w-full border rounded-lg p-3 mt-5" rows="12" value={selected} onChange={e=>change(q,e.target.value)}/>:<input autoFocus aria-label="Хариулт" className="w-full border rounded-lg p-3 mt-5" value={selected} onChange={e=>change(q,e.target.value)}/>}</fieldset></section>
<nav aria-label="Асуултын навигаци" className="flex justify-between"><button className="btn" disabled={index===0} onClick={()=>setIndex(index-1)}>← Өмнөх <kbd>Alt+←</kbd></button><div className="flex flex-wrap gap-1">{attempt.quiz.questions.map((x,i)=><button aria-label={`${i+1}-р асуулт${answers[x.id]!==undefined?', хариулсан':''}`} aria-current={i===index?'step':undefined} className={`w-9 h-9 rounded ${i===index?'bg-indigo-600 text-white':answers[x.id]!==undefined?'bg-emerald-100':'bg-slate-100'}`} onClick={()=>setIndex(i)} key={x.id}>{i+1}</button>)}</div><button className="btn" disabled={index===attempt.quiz.questions.length-1} onClick={()=>setIndex(index+1)}>Дараах → <kbd>Alt+→</kbd></button></nav>{!online&&<div role="status" className="flex gap-2 text-amber-700"><AlertTriangle/>Хариулт төхөөрөмж дээр түр хадгалагдана.</div>}</main>;}
