import {useCallback,useEffect,useState} from 'react';import {useParams} from 'react-router-dom';import {Plus,Save} from 'lucide-react';import PageHeader from '../../components/ui/PageHeader';import {createQuizQuestion,fetchQuiz,updateQuiz} from '../../services/api';import useUnsavedChanges from '../../hooks/useUnsavedChanges';
const types=['SINGLE_CHOICE','MULTIPLE_SELECT','TRUE_FALSE','SHORT_ANSWER','ESSAY'];
const SETTING_LABELS = {
  shuffleQuestions: { label:'Асуултын дараалал холих', hint:'Оролдлого бүрт асуултын дараалал санамсаргүй болно.' },
  shuffleOptions: { label:'Сонголтын дараалал холих', hint:'Олон сонголттой асуултын хариултын дараалал холигдоно.' },
  showResults: { label:'Оноо, зөв хариултыг харуулах', hint:'Идэвхгүй бол оюутан зөвхөн илгээгдсэнийг л харна, оноогоо шууд харахгүй.' },
  highStakes: { label:'Өндөр эрсдэлтэй шалгалт', hint:'Focus lost, reconnect зэрэг proctoring event илүү нарийн бүртгэгдэнэ.' },
};
export default function QuizEditor(){const {id}=useParams();const [quiz,setQuiz]=useState(null);const [q,setQ]=useState(null);const [snapshot,setSnapshot]=useState('');const load=useCallback(()=>fetchQuiz(id).then(value=>{setQuiz(value);setSnapshot(JSON.stringify(value));}),[id]);useEffect(()=>{load();},[load]);useUnsavedChanges(Boolean(q)||(quiz&&snapshot&&JSON.stringify(quiz)!==snapshot));if(!quiz)return <p>Ачааллаж байна...</p>;
const saveSettings=async()=>{await updateQuiz(id,{title:quiz.title,description:quiz.description,status:quiz.status,timeLimitMins:quiz.timeLimitMins,passingScore:quiz.passingScore,maxAttempts:quiz.maxAttempts,scoringPolicy:quiz.scoringPolicy,shuffleQuestions:quiz.shuffleQuestions,shuffleOptions:quiz.shuffleOptions,showResults:quiz.showResults,highStakes:quiz.highStakes});await load();};
const add=async e=>{e.preventDefault();const options=q.optionsText.split('\n').filter(Boolean).map((text,i)=>({id:String(i+1),text}));const correct=q.type==='MULTIPLE_SELECT'?q.correctAnswer.split(',').map(x=>x.trim()):q.correctAnswer||null;await createQuizQuestion(id,{text:q.text,type:q.type,options,correctAnswer:correct,points:Number(q.points),explanation:q.explanation||null,tags:q.tags.split(',').filter(Boolean).map(x=>x.trim()),difficulty:q.difficulty,isBankQuestion:q.isBankQuestion});setQ(null);load();};
return <div className="space-y-6"><PageHeader title="Quiz settings" subtitle={quiz.title} right={<button className="btn-primary" onClick={saveSettings}><Save size={16}/>Хадгалах</button>}/><section className="panel quiz-form grid md:grid-cols-3 gap-3"><label>Нэр<input value={quiz.title} onChange={e=>setQuiz({...quiz,title:e.target.value})}/></label><label>Төлөв<select value={quiz.status} onChange={e=>setQuiz({...quiz,status:e.target.value})}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label>Хугацаа<input type="number" value={quiz.timeLimitMins||''} onChange={e=>setQuiz({...quiz,timeLimitMins:e.target.value?Number(e.target.value):null})}/></label><label>Тэнцэх хувь<input type="number" value={quiz.passingScore} onChange={e=>setQuiz({...quiz,passingScore:Number(e.target.value)})}/></label><label>Оролдлого<input type="number" value={quiz.maxAttempts} onChange={e=>setQuiz({...quiz,maxAttempts:Number(e.target.value)})}/></label><label>Оноо тооцох арга<select value={quiz.scoringPolicy} onChange={e=>setQuiz({...quiz,scoringPolicy:e.target.value})}><option value="LATEST">Сүүлийн оролдлого</option><option value="HIGHEST">Хамгийн өндөр оролдлого</option></select></label>{Object.entries(SETTING_LABELS).map(([k,meta])=><label key={k} title={meta.hint} className="flex items-start gap-2"><input type="checkbox" className="mt-0.5" checked={quiz[k]} onChange={e=>setQuiz({...quiz,[k]:e.target.checked})}/><span>{meta.label}<span className="block text-xs text-slate-400 font-normal">{meta.hint}</span></span></label>)}</section>
<div className="flex justify-between"><h2 className="font-semibold text-xl">Асуултууд</h2><button className="btn-primary" onClick={()=>setQ({text:'',type:'SINGLE_CHOICE',optionsText:'',correctAnswer:'',points:1,explanation:'',tags:'',difficulty:'MEDIUM',isBankQuestion:true})}><Plus size={16}/>Асуулт</button></div>
{q&&<form onSubmit={add} className="panel quiz-form grid md:grid-cols-2 gap-3"><label className="md:col-span-2">Асуулт<textarea required value={q.text} onChange={e=>setQ({...q,text:e.target.value})}/></label><label>Төрөл<select value={q.type} onChange={e=>setQ({...q,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Оноо<input type="number" value={q.points} onChange={e=>setQ({...q,points:e.target.value})}/></label><label>Сонголтууд (мөр бүрт)<textarea value={q.optionsText} onChange={e=>setQ({...q,optionsText:e.target.value})}/></label><label>Зөв хариулт (option №; multiple бол таслал)<input value={q.correctAnswer} onChange={e=>setQ({...q,correctAnswer:e.target.value})}/></label><label>Tag<input value={q.tags} onChange={e=>setQ({...q,tags:e.target.value})}/></label><label>Difficulty<select value={q.difficulty} onChange={e=>setQ({...q,difficulty:e.target.value})}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><button className="btn-primary">Нэмэх</button></form>}
<div className="space-y-3">{quiz.questionLinks.map((link,i)=><article className="panel" key={link.id}><span className="text-xs text-indigo-600">{link.question.type} · {link.question.difficulty} · {link.question.points} оноо</span><h3 className="font-medium mt-1">{i+1}. {link.question.text}</h3><div className="flex gap-1 mt-2">{link.question.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div></article>)}</div></div>;}
