import { Request,Response } from 'express';import * as quiz from '../services/quiz.service';
const ctx=(r:Request)=>({org:r.organizationId!,actor:r.user!});
export const list=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.list(c.org,c.actor,r.query)});};
export const get=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.get(c.org,r.params.id,c.actor)});};
export const create=async(r:Request,s:Response)=>{const c=ctx(r);s.status(201).json({success:true,data:await quiz.create(c.org,c.actor,r.body)});};
export const update=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.update(c.org,r.params.id,c.actor,r.body)});};
export const remove=async(r:Request,s:Response)=>{const c=ctx(r);await quiz.remove(c.org,r.params.id,c.actor);s.status(204).send();};
export const bank=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.bank(c.org,c.actor,r.query)});};
export const createQuestion=async(r:Request,s:Response)=>{const c=ctx(r);s.status(201).json({success:true,data:await quiz.createQuestion(c.org,r.params.id,c.actor,r.body)});};
export const updateQuestion=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.updateQuestion(c.org,r.params.id,c.actor,r.body)});};
export const deleteQuestion=async(r:Request,s:Response)=>{const c=ctx(r);await quiz.deleteQuestion(c.org,r.params.id,c.actor);s.status(204).send();};
export const link=async(r:Request,s:Response)=>{const c=ctx(r);s.status(201).json({success:true,data:await quiz.linkBankQuestion(c.org,r.params.id,c.actor,r.body.questionId)});};
export const unlink=async(r:Request,s:Response)=>{const c=ctx(r);await quiz.unlinkQuestion(c.org,r.params.id,c.actor,r.params.questionId);s.status(204).send();};
export const start=async(r:Request,s:Response)=>s.status(201).json({success:true,data:await quiz.start(r.organizationId!,r.params.id,r.user!.userId)});
export const resume=async(r:Request,s:Response)=>s.json({success:true,data:await quiz.resume(r.organizationId!,r.params.attemptId,r.user!.userId)});
export const save=async(r:Request,s:Response)=>s.json({success:true,data:await quiz.saveAnswer(r.organizationId!,r.params.attemptId,r.params.questionId,r.user!.userId,r.body.answer)});
export const submit=async(r:Request,s:Response)=>s.json({success:true,data:await quiz.submit(r.organizationId!,r.params.attemptId,r.user!.userId)});
export const history=async(r:Request,s:Response)=>s.json({success:true,data:await quiz.history(r.organizationId!,r.params.id,r.user!.userId)});
export const grade=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.gradeAnswer(c.org,r.params.attemptId,r.params.questionId,c.actor,r.body)});};
export const analytics=async(r:Request,s:Response)=>{const c=ctx(r);s.json({success:true,data:await quiz.analytics(c.org,r.params.id,c.actor)});};
export const audit=async(r:Request,s:Response)=>s.status(201).json({success:true,data:await quiz.recordAudit(r.organizationId!,r.params.attemptId,r.user!.userId,r.body.eventType,r.body.metadata)});
